# This rule is not used by the project k8s-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over crd.sam.test.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-admin-role
rules:
- apiGroups:
  - crd.sam.test
  resources:
  - podtrackers
  verbs:
  - '*'
- apiGroups:
  - crd.sam.test
  resources:
  - podtrackers/status
  verbs:
  - get
